site_name: Seeed Wiki

pages:
- Home: index.md

- Platform:
    - Arduino:
        - Seeeduino V4.2: Platform/Arduino/SeeeduinoV4.2.md
        
    - Raspberry Pi: 
        - Raspberry Pi: Platform/RaspberryPi/RaspberryPi.md
    
    - Edison: 
        - Intel Edison: Platform/Edison/Edison.md
    
    - LaunchPad: 
        - TI LaunchPad: Platform/LaunchPad/LaunchPad.md
    
    - LinkIt: 
        - LinkIt ONE: Platform/LinkIt/LinkIt_ONE.md
    
    - mbed:
        - mbdd: Platform/mbed/mbed.md
        
    - RePhone:
        - RePhone: Platform/RePhone/RePhone.md
    
    - Wio:
        - Wio: Platform/Wio/Wio.md
    
- Grove:
    - Sensor:
        - Grove - Barometer Sensor(BMP280): Grove/Sensor/Grove_Barometer_Sensor_BMP280.md

    - Actuator:
        - Actuator: Grove/Actuator/Actuator.md
    
    - Display:
        - Display: Grove/Display/Display.md
    
    - Communication:
        - Communication: Grove/Communication/Communication.md

- IoT:
    - IoT: IoT/IoT.md

- Tutorial:
    - Tutorial: Tutorial/Tutorial.md

- SZ2U:
    - SZ2U: SZ2U/SZ2U.md
    
- About: 
    - About: about.md
    - Test: test.md
    
    
markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - smarty