site_name: Seeed Wiki

pages:
- Home: index.md

- Platform:
    - Arduino:
        - 2.8&#39;&#39; TFT Touch Shield v2.0: 2.8inch_TFT_Touch_Shield_v2.0.md
        - Base Shield V2: Base_Shield_V2.md
        - CAN-BUS Shield V1.2: CAN-BUS_Shield_V1.2.md
        - Motor Shield V2.0: Motor_Shield_V2.0.md
        - Relay Shield v3.0: Relay_Shield_v3.md
        - Seeeduino Cloud: Seeeduino_Cloud.md
        - Seeeduino GPRS: Seeeduino_GPRS.md
        - Seeeduino Lotus: Seeeduino_Lotus.md
        - Seeeduino Mega: Seeeduino_Mega.md
        - Seeeduino Stalker V3.1: Seeeduino_Stalker_V3.1.md
        - Seeeduino v4.2: Seeeduino_v4.2.md

    - BeagleBone:
        - BeagleBone Green: BeagleBone_Green.md
        - BeagleBone Green Wireless: BeagleBone_Green_Wireless.md

    - Raspberry Pi:
        - Raspberry Pi: Raspberry_Pi.md

    - LinkIt:
        - Arduino Breakout for LinkIt Smart 7688 Duo: Arduino_Breakout_for_LinkIt_Smart_7688_Duo.md
        - Breakout for LinkIt Smart 7688 v2.0: Breakout_for_LinkIt_Smart_7688_v2.0.md
        - Breakout for LinkIt Smart 7688 v2.0: Breakout_for_LinkIt_Smart_7688_v2_0.md
        - Grove Breakout for LinkIt Smart 7688 Duo: Grove-Breakout_for_LinkIt_Smart_7688_Duo.md
        - LinkIt ONE: LinkIt_ONE.md
        - LinkIt Smart 7688 Duo: LinkIt_Smart_7688_Duo.md

    - mbed:
        - Arch BLE: Arch_BLE.md

    - RePhone:
        - Arduino IDE for RePhone Kit: Arduino_IDE_for_RePhone_Kit.md
        - RePhone: Rephone.md
        - Xadow - LED 5x7: Xadow_LED_5x7.md
        - Xadow 1.54&#39;&#39; Touchscreen: Xadow_1.54_inch_Touchscreen.md
        - Xadow Audio: Xadow_Audio.md
        - Xadow Basic Sensors: Xadow_Basic_Sensors.md
        - Xadow Duino: Xadow_Duino.md
        - Xadow GPS V2: Xadow_GPS_V2.md
        - Xadow GSM Breakout: Xadow_GSM_Breakout.md
        - Xadow GSM&#43;BLE: Xadow_GSMPlusBLE.md

    - Wio:
        - Wio Link: Wio_Link.md
        - Wio Node: Wio_Node.md

    - Others:
        - Platform Others: Platform_Others.md


- Grove:
    - Grove System: Grove_System.md
    - Sensor:
        - Grove - 3 Axis Digital Accelerometer(±16g): Grove_3_Axis_Digital_Accelerometer_Plus_Minus_16g.md
        - Grove - Air Quality Sensor v1.3: Grove-Air_Quality_Sensor_v1.3.md
        - Grove - Barometer Sensor (BMP280): Grove-Barometer_Sensor-BMP280.md
        - Grove - Dust Sensor: Grove-Dust Sensor.md
        - Grove - Gas Sensor(O₂): Grove-Gas_Sensor-O2.md
        - Grove - Gesture V1.0: Grove_gesture_v1.md
        - Grove - Light Sensor: Grove-Light_Sensor.md
        - Grove - Line Finder: Grove_Line_Finder.md
        - Grove - Moisture Sensor: Grove_Moisture_Sensor.md
        - Grove - PIR Motion Sensor: Grove_PIR_Motion_Sensor.md
        - Grove - Sound Sensor: Grove-Sound_Sensor.md
        - Grove - Speech Recognizer: Grove_Speech_Recognizer.md
        - Grove - Temperature Sensor V1.2: Grove - Temperature Sensor V1.2.md
        - Grove - Temperature and Humidity Sensor: Grove_Temperature_and_Humidity_Sensor.md
        - Grove - Temperature and Humidity Sensor Pro: Grove-Temperature_and_Humidity_Sensor_Pro.md
        - Grove - Ultrasonic Ranger: Grove_Ultrasonic_Ranger.md

    - Actuator:
        - Actuator: Actuator.md
        - Grove - Button: Grove_Button.md
        - Grove - Buzzer: Grove_Buzzer.md
        - Grove - Recorder V3: Grove_Recorder_V3.md
        - Grove - Relay: Grove-Relay.md

    - Display:
        - Grove - LCD RGB Backlight: Grove-LCD_RGB_Backlight.md
        - Grove - OLED Display 0.96 inch: Grove_OLED_Display_0.96.md
        - Grove - OLED Display 1.12&#34;: Grove-OLED_Display_1.12inch.md
        - I2C LCD: I2C_LCD.md

    - Communication:
        - Communication: Communication.md
        - Grove - UART Wi-Fi: Grove-UART_Wifi.md


- IoT:
        - BLE Carbon: BLE-Carbon.md
        - BLE Nitrogen: BLE-Nitrogen.md
        - BeagleBone Green: BeagleBone_Green.md
        - BeagleBone Green Wireless: BeagleBone_Green_Wireless.md
        - Microsoft IoT Grove Kit (Azure Certified): Microsoft_IoT_Grove_Kit.md
        - Seeeduino Cloud: Seeeduino_Cloud.md
        - Seeeduino GPRS: Seeeduino_GPRS.md


- Tutorial:
        - Survey: survey_end.md
        - FM Receiver: FM_Receiver.md
        - How to install an Arduino library: How_to_Install_an_Arduino_Library.md


- MakerPro:
        - Maker Pro: MakerPro.md


<<<<<<< HEAD

=======
- 404: 404.md
        
>>>>>>> 465d4357e72657014312775c0ebcf9fcf538df9d
theme_dir: mkdocs/themes/readthedocs

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - smarty
