site_name: Seeed Wiki

pages:
- Home: index.md

- Platform:
    - Arduino:
        - Seeeduino V4.2: Platform/Arduino/SeeeduinoV4.2.md
        - CAN-BUS Shield: Platform/Arduino/CAN_BUS_Shield.md
        
    - Raspberry Pi: 
        - Raspberry Pi: Platform/RaspberryPi/RaspberryPi.md
    
    - Edison: 
        - Intel Edison: Platform/Edison/Edison.md
    
    - LaunchPad: 
        - TI LaunchPad: Platform/LaunchPad/LaunchPad.md
    
    - LinkIt: 
        - LinkIt ONE: Platform/LinkIt/LinkIt_ONE.md
        - Breakout for LinkIt Smart 7688 V2.0: Platform/LinkIt/Breakout_for_LinkIt_Smart_7688_v2_0.md
    
    - mbed:
        - mbed: Platform/mbed/mbed.md
        - Arch BLE: Platform/mbed/Arch_BLE.md
        
    - RePhone:
        - RePhone: Platform/RePhone/RePhone.md
    
    - Wio:
        - Wio Node: Platform/Wio/Wio_Node.md
    
- Grove:
    - Sensor:
        - Grove - Barometer Sensor(BMP280): Grove/Sensor/Grove_Barometer_Sensor_BMP280.md

    - Actuator:
        - Actuator: Grove/Actuator/Actuator.md
    
    - Display:
        - Display: Grove/Display/Display.md
    
    - Communication:
        - Communication: Grove/Communication/Communication.md

- IoT:
    - IoT: IoT/IoT.md
    - Microsoft IoT Grove Kit: IoT/Microsoft_IoT_Grove_Kit.md
    - Breakout for LinkIt Smart 7688 V2.0: Platform/LinkIt/Breakout_for_LinkIt_Smart_7688_v2_0.md

- Tutorial:
    - Tutorial: Tutorial/Tutorial.md

- SZ2U:
    - SZ2U: SZ2U/SZ2U.md
    
- About: 
    - About: about.md
    - 如何添加一篇文档: Tutorial/update_wiki.md
    - 文档移植:
        - 需要做什么: Port/port_main.md
        - 文档审核: Port/port_review.md
        - Github的使用: Port/port_github.md
        - Markdown: Port/port_markdown.md
        - 一个例子: Port/port_example.md
        - 常用格式代码: Port/port_normal.md
        
- Wiki migration manuals for Seeedia team:
        - Review the Wiki: Wiki migration manuals for Seeedia team/Review_the_Wiki.md
        - How to use github: Wiki migration manuals for Seeedia team/How_to_use_github.md
        - Mark Down: Wiki migration manuals for Seeedia team/Mark_Down.md
        - Summary: Wiki migration manuals for Seeedia team/Summary.md
        
-New System Style:
        - New System Style: New document system style/New_system_style.md 
        
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - smarty
