site_name: Seeed Wiki

pages:
- Home: index.md

- Platform:
    - Arduino:
        - CAN-BUS Shield: CAN_BUS_Shield.md
        - Motor Shield V2.0: Motor_Shield_V2.0.md
        - Seeeduino Lotus: Seeeduino_Lotus.md
        - Seeeduino Stalker V3.1: Seeeduino_Stalker_V3_1.md
        - Seeeduino V4: SeeeduinoV4.2.md
        - TFT Touch Shield: TFT_Touch_Shield_V2.md

    - BeagleBone:
        - BeagleBone Green: BeagleBone_Green.md
        - BeagleBone Green Wireless: BeagleBone_Green_Wireless.md

    - Raspberry Pi:
        - Raspberry Pi: RaspberryPi.md

    - Edison:
        - Intel Edison: Edison.md

    - LaunchPad:
        - TI LaunchPad: LaunchPad.md

    - LinkIt:
        - Breakout for LinkIt Smart 7688 v2.0: Breakout_for_LinkIt_Smart_7688_v2_0.md
        - Linkit ONE: LinkIt_ONE.md

    - mbed:
        - mbed: mbed.md
        - Arch BLE: Arch_BLE.md

    - RePhone:
        - RePhone: RePhone.md
        - Arduino IDE for RePhone: Arduino_IDE_for_RePhone.md
        - Xadow GSM&#43;BLE: Xadow_GSM_BLE.md

    - Wio:
        - Wio Link: Wio_Link.md
        - Wio Node: Wio_Node.md

    
- Grove:
    - Grove System: Grove_System.md
    - Sensor:
        - Grove - Barometer Sensor (BMP280): Grove_Barometer_Sensor_BMP280.md
        - Grove - Light Sensor: Grove_Light_Sensor.md
        - Grove - Sound Sensor: Grove_Sound_Sensor.md

    - Actuator:
        - Actuator: Actuator.md
    
    - Display:
        - Grove - LCD RGB Backlight: Grove_LCD_RGB_Backlight.md
        - Grove - OLED Display 1.12: Grove_OLED_Dispaly_1.12.md
        - I2C_LCD: I2C_LCD.md
  
    - Communication:
        - Communication: Communication.md


- IoT:
        - IoT: IoT.md
        - Microsoft IoT Grove Kit (Azure Certified): Microsoft_IoT_Grove_Kit.md


- Tutorial:
        - Survey: survey_end.md
        - How to install an Arduino library: How_to_Install_an_Arduino_Library.md
    

- MakerPro:
        - SZ2U: SZ2U.md


        
theme_dir: mkdocs/themes/readthedocs

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
    - smarty
