site_name: Seeed Wiki
pages:
- Home: index.md

- Platform:
	- Arduino:
		- Seeeduino V4.2: Platform/Arduino/SeeeduinoV4.2.md
	
	- Raspberry Pi:
	
	- LinkIt:
		- LinkIt ONE: Platform/LinkIt/LinkIt_ONE.md
	
	- RePhone:
	
	- Wio:
	
	- BeagleBone
	
	- Intel Edison
	
	- mbed
	
	- LaunchPad

- Grove:
	- Sensor:
		- Grove - Barometer Sensor(BMP280):Grove/Sensor/Grove_Barometer_Sensor_BMP280.md
	
	- Actuator:
	
	- Display
	
	- Communication
	
- Shield:

- Robot:

- About: about.md