site_name: Seeed Wiki
pages:
- Home: index.md

- Platform:
    - Arduino:
        - Seeeduino V4.2: Platform/Arduino/SeeeduinoV4.2.md
        
    - Raspberry Pi: Platform/Arduino/SeeeduinoV4.2.md
    
- Grove:
    - Sensor:
        - Grove - Barometer Sensor(BMP280): Grove/Sensor/Grove_Barometer_Sensor_BMP280.md

- About: 
    - About: about.md
    - Test: test.md